/**
 * Data Loader - Smart static-first data loading with optional live fallback
 *
 * This module provides a secure way to load camp data:
 * 1. Primary: Load from static snapshot (no API keys exposed)
 * 2. Optional: Load from Airtable (development/testing only with ?source=airtable)
 * 3. Fallback: Generate mock data for testing
 *
 * @module dataLoader
 */

import campsSnapshot from '../data/camps-snapshot.json';
import { generateMockData } from './mockData';
import { logger } from './logger';

/**
 * Load camps from static snapshot file
 *
 * This is the primary data source for production builds.
 * The snapshot file is generated by running `npm run update-data`.
 *
 * @returns {Promise<Object>} Object containing camps array and metadata
 */
export const loadStaticData = async () => {
  try {
    logger.data.info('Loading data from static snapshot');

    const camps = campsSnapshot.camps || [];
    const metadata = campsSnapshot.metadata || {
      generatedAt: new Date().toISOString(),
      source: 'static',
      totalCamps: camps.length
    };

    // Validate snapshot data
    if (!Array.isArray(camps)) {
      throw new Error('Invalid snapshot format: camps must be an array');
    }

    // Check if snapshot is a placeholder
    if (camps.length === 0 && metadata.source === 'placeholder') {
      logger.data.warn('Using placeholder snapshot. Run "npm run update-data" to fetch real data.');
    }

    logger.data.info('Static data loaded successfully', {
      totalCamps: camps.length,
      generatedAt: metadata.generatedAt,
      source: metadata.source
    });

    return {
      camps,
      metadata,
      source: 'static'
    };

  } catch (error) {
    logger.error.error('Error loading static data:', error);
    throw error;
  }
};

/**
 * Load camps from mock data generator
 *
 * Used for testing and development when no real data is available.
 * Generates realistic camp distributions across all blocks.
 *
 * @returns {Promise<Object>} Object containing camps array and metadata
 */
export const loadMockData = async () => {
  try {
    logger.data.info('Generating mock data');

    const camps = generateMockData();

    // Calculate statistics
    const stats = camps.reduce((acc, camp) => {
      acc[camp.bed_status] = (acc[camp.bed_status] || 0) + 1;
      return acc;
    }, {});

    const metadata = {
      generatedAt: new Date().toISOString(),
      source: 'mock',
      totalCamps: camps.length,
      stats
    };

    logger.data.info('Mock data generated', {
      totalCamps: camps.length,
      stats
    });

    return {
      camps,
      metadata,
      source: 'mock'
    };

  } catch (error) {
    logger.error.error('Error generating mock data:', error);
    throw error;
  }
};

/**
 * Determine which data source to use based on URL parameters
 *
 * @returns {string} Data source: 'static', 'airtable', or 'mock'
 */
export const getDataSource = () => {
  // Check URL parameters
  const urlParams = new URLSearchParams(window.location.search);
  const sourceParam = urlParams.get('source');

  if (sourceParam) {
    const validSources = ['static', 'airtable', 'mock'];
    if (validSources.includes(sourceParam.toLowerCase())) {
      return sourceParam.toLowerCase();
    }
    logger.data.warn(`Invalid data source parameter: ${sourceParam}, using static`);
  }

  // Default to static data (secure, no API calls)
  return 'static';
};

/**
 * Smart data loader that selects the appropriate source
 *
 * This is the main entry point for data loading in the application.
 *
 * @param {string} [requestedSource] - Optional explicit data source
 * @returns {Promise<Object>} Object containing camps, metadata, and source
 */
export const loadData = async (requestedSource = null) => {
  const source = requestedSource || getDataSource();

  try {
    switch (source) {
      case 'static':
        return await loadStaticData();

      case 'mock':
        return await loadMockData();

      case 'airtable':
        // Note: Airtable loading is handled by useMapData hook
        // to avoid circular dependencies
        logger.data.warn('Airtable data source requested - should be handled by useMapData hook');
        return await loadStaticData(); // Fallback to static

      default:
        logger.data.warn(`Unknown data source: ${source}, using static`);
        return await loadStaticData();
    }
  } catch (error) {
    logger.error.error('Error loading data, falling back to mock data:', error);
    return await loadMockData();
  }
};

/**
 * Validate camp data structure
 *
 * @param {Array} camps - Array of camp objects
 * @returns {Object} Validation result with valid camps and errors
 */
export const validateCamps = (camps) => {
  const validCamps = [];
  const errors = [];

  camps.forEach((camp, index) => {
    const issues = [];

    // Required fields
    if (!camp.id) issues.push('missing id');
    if (!camp.camp_name) issues.push('missing camp_name');
    if (!camp.placement_address) issues.push('missing placement_address');
    if (!camp.bed_status) issues.push('missing bed_status');

    // Valid bed_status values
    const validStatuses = ['none', 'registered', 'consent_policy', 'bed_talk'];
    if (camp.bed_status && !validStatuses.includes(camp.bed_status)) {
      issues.push(`invalid bed_status: ${camp.bed_status}`);
    }

    if (issues.length > 0) {
      errors.push({
        index,
        campName: camp.camp_name || 'Unknown',
        issues
      });
    } else {
      validCamps.push(camp);
    }
  });

  if (errors.length > 0) {
    logger.data.warn('Data validation found issues:', {
      validCamps: validCamps.length,
      invalidCamps: errors.length,
      errors: errors.slice(0, 5) // Log first 5 errors
    });
  }

  return {
    validCamps,
    errors,
    isValid: errors.length === 0
  };
};

/**
 * Get data source statistics
 *
 * @param {Array} camps - Array of camp objects
 * @returns {Object} Statistics about the data
 */
export const getDataStats = (camps) => {
  const stats = {
    total: camps.length,
    byStatus: {},
    byStreet: {},
    withBuddy: 0,
    totalCampers: 0
  };

  camps.forEach(camp => {
    // Count by status
    stats.byStatus[camp.bed_status] = (stats.byStatus[camp.bed_status] || 0) + 1;

    // Count by street (extract from placement_address)
    const addressMatch = camp.placement_address?.match(/&\s*([A-L]|Esplanade)/i);
    if (addressMatch) {
      const street = addressMatch[1].toUpperCase();
      stats.byStreet[street] = (stats.byStreet[street] || 0) + 1;
    }

    // Count camps with buddies
    if (camp.buddy_name) {
      stats.withBuddy++;
    }

    // Sum campers
    if (camp.camper_count) {
      stats.totalCampers += camp.camper_count;
    }
  });

  return stats;
};

export default {
  loadData,
  loadStaticData,
  loadMockData,
  getDataSource,
  validateCamps,
  getDataStats
};
